Models/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PikTok.Models {
    public class HomeViewModel : IMultiParametersInOneModel {
        public bool isOwner { get; set; }
        public bool isFriend { get; set; }
        public UserAccount userAccount { get; set; }
    }
}

Models/MessagesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PikTok.Models {
    public class MessageViewModel : IMultiParametersInOneModel {
        public UserAccount userAccount { get; set; }
    }
}

Models/SearchViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PikTok.Models {
    public class SearchViewModel : IMultiParametersInOneModel {
        public UserAccount userAccount { get; set; }
        public List<ProfileModel> searchResults { get; set; }
    }
}

Controllers/AuthController.cs
using System.Collections.Generic;
using PikTok.Models;
using PikTok.Services;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using System.Text.Json;
using System;
using Microsoft.AspNetCore.Http;
using System.IO;
using Firebase.Storage;
using MongoDB.Bson;

namespace PikTok.Controllers {
    [ApiController]
    [Route("[controller]")]
    public class AuthController : Controller {
        private readonly DatabaseService databaseService;
        private readonly MediaService mediaService;

        public AuthController(AuthService authService, DatabaseService databaseService, MediaService mediaService) {
            this.authService = authService;
            this.databaseService = databaseService;
            this.mediaService = mediaService;
        }

        public AuthService authService { get; }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="Email"></param>
        /// <param name="Password"></param>
        /// <returns></returns>
        [HttpPost("Login")]
        public async Task<ActionResult> Login([FromForm] string Email, [FromForm] string Password) {
            //Checks and retrievs user
            var userAccount = await authService.AuthenticateUser(Email, Password);
            if (userAccount != null) {
                //Gets the jwt token
                AuthToken authToken = authService.GetToken(userAccount);
                string jsd = JsonSerializer.Serialize(authToken);
                Console.WriteLine(jsd);
                //Writes to cookies
                Response.Cookies.Append("Token", jsd);
            }
            else {
                return View("cta");
            }
            return Redirect("/");
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="registerForm"></param>
        /// <returns></returns>
        [HttpPost("Register")]
        public async Task<ActionResult> Register([FromForm] string Email, [FromForm] string UserName, [FromForm] string Password, [FromForm] IFormFile ProfilePhoto) {
            bool exsist = await databaseService.CheckIfEmailIsTaken(Email);
            if (exsist) { return View("cta"); }
            //Creates the account in the database service
            UserAccount userAccount = await databaseService.CreateAccount(new UserAccount() {
                Email = Email,
                Password = Password,
                profile = new ProfileModel() {
                    UserName = UserName
                }
            });
            //If there is a profile pifture in the form, this updates the record in the database after uploading the image to firebase
            if (ProfilePhoto != null) {
                userAccount.profile.ProfilePicture = new Media() {
                    mediaType = TypeOfMedia.Image,
                    url = await mediaService.UpdateProfilePicture(ProfilePhoto, userAccount.userId)
                };
                _ = databaseService.UpdateUserAccount(userAccount.profile, nameof(userAccount.profile), userAccount.userId, null);
            }
            //Gets the model that contains the JWT token
            AuthToken authToken = authService.GetToken(userAccount);
            string jsd = JsonSerializer.Serialize(authToken);
            //Adds the token to client's Cookies
            Response.Cookies.Append("Token", jsd);
            return Redirect("/");
        }
        public class RegisterForm {
            
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PikTok.Components;
using PikTok.Models;
using PikTok.Services;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Text.Json;
using System.Threading.Tasks;

namespace PikTok.Controllers {
    [Route("")]
    public class HomeController : Controller {
        IWebHostEnvironment webHostEnvironment;
        private readonly IHtmlHelper htmlHelper;

        public HomeController(AuthService authService, DatabaseService databaseService, IWebHostEnvironment webHostEnvironment, IHtmlHelper htmlHelper) {
            this.authService = authService;
            this.databaseService = databaseService;
            this.webHostEnvironment = webHostEnvironment;
            this.htmlHelper = htmlHelper;
        }
        public AuthService authService { get; }
        private readonly DatabaseService databaseService;
        public async Task<IActionResult> Home() {
            //Checks if cookies contains Token
            if (!Request.Cookies.ContainsKey("Token")) {
                return View("cta");
            }
            //Gets user with token
            UserAccount userAccount = await authService.GetUser(Request.Cookies);
            return View("home", new HomeViewModel() {
                userAccount = userAccount
            });
        }
        [HttpPost("Follow")]
        public async Task<IActionResult> Follow(string UserName) {
            //Checks if cookies contains Token
            if (!Request.Cookies.ContainsKey("Token")) {
                return View("cta");
            }
            //Gets user with token
            UserAccount userAccount = await authService.GetUser(Request.Cookies);
            await databaseService.Follow(UserName, userAccount);
            return Ok();
        }
        [HttpGet("GetExternalId")]
        public async Task<IActionResult> GetExternalId() {
            //Checks if cookies contains Token
            if (!Request.Cookies.ContainsKey("Token")) {
                return Unauthorized();
            }
            //Gets user with token
            UserAccount userAccount = await authService.GetUser(Request.Cookies);
            return Ok(userAccount.externalUserId);
        }
    }
}

Controllers/MessagesController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PikTok.Models;
using PikTok.Models.PacketModels;
using PikTok.Services;
using System;
using System.Threading.Tasks;

namespace PikTok.Controllers {
    [ApiController]
    [Route("[controller]")]
    public class MessagesController : Controller {
        public MessagesController(AuthService authService, DatabaseService databaseService) {
            this.authService = authService;
            this.databaseService = databaseService;
        }
        public AuthService authService { get; }
        private readonly DatabaseService databaseService;
        [HttpGet]
        public async Task<IActionResult> Home() {
            //Checks if cookies contains Token
            if (!Request.Cookies.ContainsKey("Token")) { return View("cta"); }
            UserAccount userAccount = await authService.GetUser(Request.Cookies);
            foreach (ChatModel chat in userAccount.chats) {

            }
            return View("Messages", new HomeViewModel() {
                userAccount = userAccount
            });
        }
        [HttpGet("GetChats")]
        public async Task<IActionResult> GetChats() {
            if (!Request.Cookies.ContainsKey("Token")) {
                return View("cta");
            }
            UserAccount userAccount = await authService.GetUser(Request.Cookies);
            if (userAccount == null) { return View("cta"); }
            foreach(ChatModel chat in userAccount.chats) {
                var acc = await authService.GetUserWithExternalId(chat.externalUserId);
                chat.userName = acc.profile.UserName;
                chat.profilePictureUrl = acc.profile.ProfilePicture.url;
            }
            return Ok(userAccount.chats);
        }
        [HttpGet("GetUsername")]
        public async Task<IActionResult> GetUsername(string externalUserId) {
            if (!Request.Cookies.ContainsKey("Token")) {
                return View("cta");
            }
            UserAccount userAccount = await authService.GetUserWithExternalId(externalUserId);
            if (userAccount == null) { return NotFound(externalUserId); }
            return Ok(userAccount.profile.UserName);
        }
    }
}

Controllers/SearchController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PikTok.Components;
using PikTok.Models;
using PikTok.Services;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Text.Json;
using System.Threading.Tasks;

namespace PikTok.Controllers {
    [ApiController]
    [Route("[controller]")]
    public class SearchController : Controller {
        IWebHostEnvironment webHostEnvironment;
        private readonly IHtmlHelper htmlHelper;

        public SearchController(AuthService authService, DatabaseService databaseService) {
            this.authService = authService;
            this.databaseService = databaseService;
        }
        public AuthService authService { get; }
        private readonly DatabaseService databaseService;
        [HttpGet]
        public async Task<IActionResult> Search(string queryString) {
            //Checks if cookies contains Token
            if (!Request.Cookies.ContainsKey("Token")) { return View("cta"); }
            UserAccount userAccount = await authService.GetUser(Request.Cookies);
            var list = await databaseService.Search(queryString);
            return View("Search", new SearchViewModel() {
                userAccount = userAccount,
                searchResults = list
        });
        }
    }
}

Views/Shared/Cta.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using PikTok.Components
@using PikTok.Models
@using PikTok.Services
@using Microsoft.AspNetCore.Components.Web
@{
    ViewData["Title"] = "PikTok";
}

<!DOCTYPE html>
<html lang="en" style="font-family: 'Bai Jamjuree', sans-serif;">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>New page</title>
    <link rel="stylesheet" href="https://unpkg.com/tailwindcss@1.6.0/dist/tailwind.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Akronim&display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Allerta+Stencil&display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Atomic+Age&display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Audiowide&display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bai+Jamjuree&display=swap">
</head>
<body style="">
    <style>
        body {
            background-color: #dedede;
            background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='800' height='800' viewBox='0 0 200 200'%3E%3Cdefs%3E%3ClinearGradient id='a' gradientUnits='userSpaceOnUse' x1='88' y1='88' x2='0' y2='0'%3E%3Cstop offset='0' stop-color='%238f8408'/%3E%3Cstop offset='1' stop-color='%23e3d10d'/%3E%3C/linearGradient%3E%3ClinearGradient id='b' gradientUnits='userSpaceOnUse' x1='75' y1='76' x2='168' y2='160'%3E%3Cstop offset='0' stop-color='%238f8f8f'/%3E%3Cstop offset='0.09' stop-color='%23b3b3b3'/%3E%3Cstop offset='0.18' stop-color='%23c9c9c9'/%3E%3Cstop offset='0.31' stop-color='%23dbdbdb'/%3E%3Cstop offset='0.44' stop-color='%23e8e8e8'/%3E%3Cstop offset='0.59' stop-color='%23f2f2f2'/%3E%3Cstop offset='0.75' stop-color='%23fafafa'/%3E%3Cstop offset='1' stop-color='%23ffffff'/%3E%3C/linearGradient%3E%3Cfilter id='c' x='0' y='0' width='200%25' height='200%25'%3E%3CfeGaussianBlur in='SourceGraphic' stdDeviation='12' /%3E%3C/filter%3E%3C/defs%3E%3Cpolygon fill='url(%23a)' points='0 174 0 0 174 0'/%3E%3Cpath fill='%23000' fill-opacity='.5' filter='url(%23c)' d='M121.8 174C59.2 153.1 0 174 0 174s63.5-73.8 87-94c24.4-20.9 87-80 87-80S107.9 104.4 121.8 174z'/%3E%3Cpath fill='url(%23b)' d='M142.7 142.7C59.2 142.7 0 174 0 174s42-66.3 74.9-99.3S174 0 174 0S142.7 62.6 142.7 142.7z'/%3E%3C/svg%3E");
            background-attachment: fixed;
            background-repeat: no-repeat;
            background-position: top left;
        }
    </style>
    <div class="flex items-center justify-center min-h-screen min-w-screen px-5 py-5">
        <div></div>
        <div class="rounded-3xl w-full overflow-hidden" style="max-width:1000px">
            <div class="md:flex w-full">
                <div class="hidden md:block p-5 w-full md:px-10 md:w-1/2">
                    <img src="Resources/OnlyPhones.png" alt="" />
                </div>
                <div class="bg-gray-100 bg-opacity-0 p-5 w-full md:px-10 md:w-1/2">
                    <div class="text-center mb-10">
                        <h1 class="font-bold text-3xl text-yellow-600">PikTok</h1>
                        <p>lorem</p>
                    </div>

                    <form asp-controller="Auth" asp-action="Login" method="post">
                        <div class="flex -mx-3">
                        </div>
                        <div class="flex -mx-3">
                            <div class="w-full px-3 mb-5">
                                <label for="" class="text-xs font-semibold px-1">Email</label>
                                <div class="flex">
                                    <div class="w-10 z-10 pl-1 text-center pointer-events-none flex items-center justify-center">
                                        <i class="mdi mdi-email-outline text-gray-400 text-lg"></i>
                                    </div>
                                    <input name="Email" type="email" class="w-full -ml-10 pl-10 pr-3 py-2 rounded-lg border-2 border-gray-200 outline-none focus:border-indigo-500" placeholder="johnsmith@example.com">
                                </div>
                            </div>
                        </div>
                        <div class="flex -mx-3">
                            <div class="w-full px-3 mb-12">
                                <label for="" class="text-xs font-semibold px-1">Password</label>
                                <div class="flex">
                                    <div class="w-10 z-10 pl-1 text-center pointer-events-none flex items-center justify-center">
                                        <i class="mdi mdi-lock-outline text-gray-400 text-lg"></i>
                                    </div>
                                    <input name="Password" type="password" class="w-full -ml-10 pl-10 pr-3 py-2 rounded-lg border-2 border-gray-200 outline-none focus:border-indigo-500" placeholder="************">
                                </div>
                            </div>
                        </div>
                        <div class="flex -mx-3">
                            <div class="w-full px-3 mb-5">
                                <button class="-mt-8 bg-yellow-500 block focus:bg-yellow-600 font-semibold hover:bg-yellow-600 max-w-xs mx-auto p-3 rounded-lg text-white w-full" type="submit">LOG IN</button>
                                <div style="background:black; width:80%; height: 1px;"></div>
                                <button class="bg-green-600 block focus:bg-green-600 font-semibold hover:bg-green-700 max-w-xs modal-open mt-8 mx-auto p-3 rounded-lg text-white w-full">REGISTER</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!--Modal-->
    <div class="modal opacity-0 pointer-events-none fixed w-full h-full top-0 left-0 flex items-center justify-center">
        <div class="modal-overlay absolute w-full h-full bg-gray-900 opacity-50"></div>
        <div class="modal-container bg-white w-11/12 md:max-w-md mx-auto rounded shadow-lg z-50 overflow-y-auto">
            <div class="modal-close absolute top-0 right-0 cursor-pointer flex flex-col items-center mt-4 mr-4 text-white text-sm z-50">
                <svg class="fill-current text-white" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
                    <path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"></path>
                </svg>
                <span class="text-sm">(Esc)</span>
            </div>
            <!-- Add margin if you want to see some of the overlay behind the modal-->
            <div class="modal-content py-4 text-left px-6">
                <!--Title-->
                <div class="flex justify-between items-center pb-3">
                    <p class="text-2xl font-bold">Register</p>
                    <div class="modal-close cursor-pointer z-50">
                        <svg class="fill-current text-black" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
                            <path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"></path>
                        </svg>
                    </div>
                </div>
                <!--Body-->
                <form asp-controller="Auth" asp-action="Register" method="post" enctype="multipart/form-data">
                    <div class="flex -mx-3">
                        <div class="w-1/2 px-3 mb-5">
                            <label for="" class="text-xs font-semibold px-1">UserName</label>
                            <div class="flex">
                                <div class="w-10 z-10 pl-1 text-center pointer-events-none flex items-center justify-center">
                                    <i class="mdi mdi-account-outline text-gray-400 text-lg"></i>
                                </div>
                                <input name="UserName" type="text" class="w-full -ml-10 pl-10 pr-3 py-2 rounded-lg border-2 border-gray-200 outline-none focus:border-indigo-500" placeholder="UserName">
                            </div>
                        </div>
                    </div>
                    <div class="flex -mx-3">
                        <div class="w-full px-3 mb-5">
                            <label for="" class="text-xs font-semibold px-1">Email</label>
                            <div class="flex">
                                <div class="w-10 z-10 pl-1 text-center pointer-events-none flex items-center justify-center">
                                    <i class="mdi mdi-email-outline text-gray-400 text-lg"></i>
                                </div>
                                <input name="Email" type="email" class="w-full -ml-10 pl-10 pr-3 py-2 rounded-lg border-2 border-gray-200 outline-none focus:border-indigo-500" placeholder="johnsmith@example.com">
                            </div>
                        </div>
                    </div>
                    <div class="flex -mx-3">
                        <div class="w-full px-3 mb-12">
                            <label for="" class="text-xs font-semibold px-1">Password</label>
                            <div class="flex">
                                <div class="w-10 z-10 pl-1 text-center pointer-events-none flex items-center justify-center">
                                    <i class="mdi mdi-lock-outline text-gray-400 text-lg"></i>
                                </div>
                                <input name="Password" type="password" class="w-full -ml-10 pl-10 pr-3 py-2 rounded-lg border-2 border-gray-200 outline-none focus:border-indigo-500" placeholder="************">
                            </div>
                        </div>
                    </div>
                    <div class="flex -mx-3">
                        <div class="w-full px-3 mb-12">
                            <label for="" class="text-xs font-semibold px-1">Password</label>
                            <div class="flex">
                                <div class="w-10 z-10 pl-1 text-center pointer-events-none flex items-center justify-center">
                                    <i class="mdi mdi-lock-outline text-gray-400 text-lg"></i>
                                </div>
                                <input name="ProfilePhoto" type="file" Class="form-control" />
                            </div>
                        </div>
                    </div>
                    <div class="flex -mx-3">
                        <div class="w-full px-3 mb-5">
                            <button type = "submit" class="bg-blue-600 block focus:bg-blue-600 font-semibold hover:bg-blue-700 max-w-xs mt-8 mx-auto p-3 rounded-lg text-white w-full">REGISTER</button>
                        </div>
                    </div>
                </form>
                <!--Footer-->
                <div class="flex justify-end pt-2">
                </div>
            </div>
        </div>
    </div>
    <style>
        .modal {
            transition: opacity 0.25s ease;
        }

        body.modal-active {
            overflow-x: hidden;
            overflow-y: visible !important;
        }
    </style>
    <script>
        var openmodal = document.querySelectorAll('.modal-open')
        for (var i = 0; i < openmodal.length; i++) {
            openmodal[i].addEventListener('click', function (event) {
                event.preventDefault()
                toggleModal()
            })
        }

        const overlay = document.querySelector('.modal-overlay')
        overlay.addEventListener('click', toggleModal)

        var closemodal = document.querySelectorAll('.modal-close')
        for (var i = 0; i < closemodal.length; i++) {
            closemodal[i].addEventListener('click', toggleModal)
        }

        document.onkeydown = function (evt) {
            evt = evt || window.event
            var isEscape = false
            if ("key" in evt) {
                isEscape = (evt.key === "Escape" || evt.key === "Esc")
            } else {
                isEscape = (evt.keyCode === 27)
            }
            if (isEscape && document.body.classList.contains('modal-active')) {
                toggleModal()
            }
        };


        function toggleModal() {
            const body = document.querySelector('body')
            const modal = document.querySelector('.modal')
            modal.classList.toggle('opacity-0')
            modal.classList.toggle('pointer-events-none')
            body.classList.toggle('modal-active')
        }


    </script>
</body>
</html>

Views/Shared/Home.cshtml
@inject PikTok.Services.PostService postService
@inject Microsoft.JSInterop.IJSRuntime JSRuntime
@model PikTok.Models.HomeViewModel
@using Microsoft.AspNetCore.Components.Web
@using PikTok.Components
@{
    ViewData["Title"] = "Home";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}
<div class="CardsContainer bg-gray-50 dark:bg-black flex flex-col items-stretch justify-center">

</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        GetHomePosts();
        window.onscroll = function (ev) {
            if ((window.innerHeight + window.scrollY) >= document.body.offsetHeight) {
                //GetHomePosts();
            }
        };
    }, false);
</script>

Views/Shared/Messages.cshtml
@inject PikTok.Services.PostService postService
@inject Microsoft.JSInterop.IJSRuntime JSRuntime
@model PikTok.Models.HomeViewModel
@using Microsoft.AspNetCore.Components.Web
@using PikTok.Components
@using PikTok.Models
@inject PikTok.Services.AuthService authService
@{
    ViewData["Title"] = "Messages";
    Layout = "~/Pages/Shared/_Layout.cshtml";


}
<div class="flex flex-col h-screen mx-auto border-gray-500 border-t messages_unopen" id="chats-display" style="overflow-y:auto">  
    
</div>



<div class="h-screen hidden" style="overflow-y:auto" id="message-display">
    <div>
        <!-- HEADING -->
        <div class="bg-yellow-400 fixed flex h-16 justify-between mt-12 pt-2 shadow-md text-white max-w-screen" style="top:0px; width: 100%; overscroll-behavior: none;">
            <!-- back button -->
            <button onclick="closeMessagesDiasplay()" href="#">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="w-12 h-12 my-1 text-green-100 ml-2">
                    <path class="text-green-100 fill-current" d="M9.41 11H17a1 1 0 0 1 0 2H9.41l2.3 2.3a1 1 0 1 1-1.42 1.4l-4-4a1 1 0 0 1 0-1.4l4-4a1 1 0 0 1 1.42 1.4L9.4 11z" />
                </svg>
            </button>
            <div>
                <img src="" class="w-12 h-12 rounded-full" alt="dp" id="chat-display-image" style="display:inline-block;" />
                <a class="text-green-100 font-bold text-lg tracking-wide" id="chat-display-name" style="display:inline-block; font-size: 25px; padding-left:20px;"></a>
            </div>
            <!-- 3 dots -->
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="icon-dots-vertical w-8 h-8 mt-2 mr-2">
                <path class="text-green-100 fill-current" fill-rule="evenodd" d="M12 7a2 2 0 1 1 0-4 2 2 0 0 1 0 4zm0 7a2 2 0 1 1 0-4 2 2 0 0 1 0 4zm0 7a2 2 0 1 1 0-4 2 2 0 0 1 0 4z" />
            </svg>
        </div>
        <!-- MESSAGES -->
        <div class="mt-20 mb-16 w-100" id="messages-container" style="position: relative; bottom: 50px !important; padding-top:30px; z-index: -100;">
            <!-- SINGLE MESSAGE -->
            <div class="clearfix">
                <div class="bg-gray-400 w-3/4 mx-4 my-2 p-2 rounded-lg">this is a basic mobile chat layout, build with tailwind css</div>
            </div>
            <!-- SINGLE MESSAGE 3 -->
            <div class="clearfix">
                <div class="bg-yellow-400 float-right w-3/4 mx-4 my-2 p-2 rounded-lg clearfix">check my twitter to see when it will be released.</div>
            </div>
        </div>
    </div>
    <!-- MESSAGE INPUT AREA -->
    <div class="fixed w-full flex justify-between bg-green-100" style="bottom: 0px;">
        <textarea class="flex-grow m-2 py-2 px-4 mr-1 rounded-full border border-gray-300 bg-gray-200 resize-none" rows="1" placeholder="Message..." style="outline: none;" id="typedMessage"></textarea>
        <button class="m-2" style="outline: none;" id="typedMessageButton" onclick="">
            <svg class="svg-inline--fa text-green-400 fa-paper-plane fa-w-16 w-12 h-12 py-2 mr-2" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="paper-plane" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                <path fill="currentColor" d="M476 3.2L12.5 270.6c-18.1 10.4-15.8 35.6 2.2 43.2L121 358.4l287.3-253.2c5.5-4.9 13.3 2.6 8.6 8.3L176 407v80.5c0 23.6 28.5 32.9 42.5 15.8L282 426l124.6 52.2c14.2 6 30.4-2.9 33-18.2l72-432C515 7.8 493.3-6.8 476 3.2z" />
            </svg>
        </button>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        GetChats();

        window.addEventListener('load', () => {
            var params = new URL(document.location).searchParams;
            var ExId = params.get('ExId');
            window.history.replaceState({}, document.title, "/Messages");
            if (ExId != null) {
                DisplayChatMessages(ExId);
            }
        });

    }, false);
</script>

<style>
    body {
        overflow: hidden;
    }
</style>